export const BRAND_SERIES: [string, string[]][] = [
  ['baby mom', []],
  ['babygo', []],
  ['baby turco', []],
  ['bella baby happy', []],
  ['brand for my son', []],
  ['cam', ['pannolino batuffi']],
  ['cushy baby', []],
  ['pampers', ['premium care', 'active baby dry', 'new baby dry']],
  ['pufies', []],
  [
    'huggies',
    [
      'elite soft platinum',
      'elite soft overnites',
      'elite soft',
      'disney girl',
      'disney boy',
      'dry nites',
      'little swimmers',
      'ultra comfort',
      'classic',
    ],
  ],
  ['happy mum', []],
  ['paddlers', []],
  ['poopeys', []],
  ['palmbaby', ['magic']],
  ['merries', ['econom']],
  ['mepsi', []],
  ['mioki', []],
  ['mykiddo', []],
  ['manu', []],
  ['noopii', []],
  ['senso baby', ['sensitive', 'simple', 'ecoline']],
  ['senso', ['simple', 'sens']],
  ['skippy', ['more happiness', 'ultra', 'pull up', 'econom']],
  ['synergetic', ['pure nature']],
  ['sleepy', []],
  ['slipers', []],
  ['softlove', ['platinum', 'smart pants']],
  ['yokosun', ['econom', 'eco', 'premium']],
  ['yumiko', []],
  ['tokisan', ['baby pull up']],
  ['dada', ['extra care', 'extra soft']],
  ['evy baby', []],
  ['lalaku', []],
  ['watashi', []],
  ['little art', []],
  ['libero', ['touch', 'comfort']],
  ['lody', []],
  ['offspring', []],
  ['kunder', []],
  ['unidry', ['ultra soft', 'premium']],
];

export const SIZES: [string, string[]][] = [
  ['7 XXXL', ['7', 'лет', 'XXXL']],
  ['6 XXL', ['6', 'large', 'XXL']],
  ['5 XL', ['5', 'junior', '5XL-junior', 'XL', 'ХL']],
  ['4 L', ['4', 'maxi', '4L-maxi', 'L']],
  ['3 M', ['3', 'midi', '3M-midi', 'M', 'М']],
  ['2 S', ['2', 'mini', '2S-mini', 'S']],
  ['0 NB XS', ['0', 'micro', 'NB XS', 'XS', 'new born xs', 'before new born']],
  ['1 NB', ['1', 'new born', 'NB', 'новорожденных']],
];
